spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cache_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
logging:
  level:
    org.ponking.cache: debug
